version: "3.8"

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=shop
    ports:
      - '5432:5432/tcp'
    networks:
      - default
